const actionTypes = {
    LOGIN: "LOGIN",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",

    GET_CAMPAIGN_BY_CATEGORY: "GET_CAMPAIGN_BY_CATEGORY",
    GET_CAMPAIGN_BY_ID: "GET_CAMPAIGN_BY_ID",

    GET_CAMPAIGNS: "GET_CAMPAIGNS",
    GET_ACTIVE_CAMPAIGNS: "GET_ACTIVE_CAMPAIGNS",
    GET_EXPIRED_CAMPAIGNS: "GET_EXPIRED_CAMPAIGNS",
    GET_NOT_APPROVED_CAMPAIGN: "GET_NOT_APPROVED_CAMPAIGN",

    GET_CAMPAIGN_ORGANIZATION: "GET_CAMPAIGN_ORGANIZATION",
    GET_ACTIVE_CAMPAIGN_ORGANIZATION: "GET_ACTIVE_CAMPAIGN_ORGANIZATION",
    GET_EXPIRED_CAMPAIGN_ORGANIZATION: "GET_EXPIRED_CAMPAIGN_ORGANIZATION",
    GET_NOT_APPROVED_CAMPAIGN_ORGANIZATION:
        "GET_NOT_APPROVED_CAMPAIGN_ORGANIZATION",

    GET_CATEGORIES: "GET_CATEGORIES",
    GET_ALL_VOLUNTEER: "GET_ALL_VOLUNTEER",
    GET_APPROVED_VOLUNTEER: "GET_APPROVED_VOLUNTEER",
    GET_NOT_APPROVED_VOLUNTEER: "GET_NOT_APPROVED_VOLUNTEER",

    PAYMENT_REQUEST: "PAYMENT_REQUEST",
    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
    PAYMENT_FAIL: "PAYMENT_FAIL",
    PAYMENT_RESET: "PAYMENT_RESET",

    REGISTER_VOLUNTEER_REQUEST: "REGISTER_VOLUNTEER_REQUEST",
    REGISTER_VOLUNTEER_SUCCESS: "REGISTER_VOLUNTEER_SUCCESS",
    REGISTER_VOLUNTEER_FAILURE: "REGISTER_VOLUNTEER_FAILURE",

    //USER
    GET_CURRENT: "GET_CURRENT",
    GET_ALL_USER: "GET_ALL_USER",

    //TASK
    GET_TASK_TYPES: "GET_TASK_TYPES",

    //Organization
    GET_ALL_ORGANIZATION: "GET_ALL_ORGANIZATION",
};

export default actionTypes;
